name: ktlint

on: [push, workflow_dispatch]

jobs:
  ktlint:
      runs-on: ubuntu-latest

      steps:
        - name: "checkout"
          uses: actions/checkout@v2

        - name: "ktlint"
          uses: "vroy/gha-kotlin-linter@v1"